<HTML>
<head>
<title>DATA PORTAL</title> <link rel="icon" href="IHRDLO2.PNG">
</head>
<HR COLOR=" #cc0000">
<body bgcolor=#C0C0C0>
		<div style = "font-size:40px; color:#cc0000; margin-top:30px">
			<center>
				<img src="IHRDLO.png"  width="140" height="100"><h3>DATA PAGE DEVIATER</h3>
			</center>
</div>
<HR COLOR=" #cc0000"><BR/><a href="LOGIN.PHP" class="txt2 hov1">
							LOGIN PAGE
			</a></body>
					<CENTER>
					<label>ENTER CLASS	:</label>
			<input type = "text" name = "CID" class = "box"/><br /><br />
						<a href="ALLDATA.PHP" class="txt2 hov1"><BR/>
							<H1> ALL STUDENT DATA<H1><BR/>
			</a>			
						<A href="DPDATA.PHP" class="txt2 hov1">
							<H1>DUE PENDING STUDENT DATA<H1>
			</a>			
						<a href="DCDATA.PHP" class="txt2 hov1">
							<H1>DUE CLEARE STUDENT DATA<H1>
			</a>
			</CENTER
			

</HTML>